name: Demo pipeline

on:
    push:
        branches: [main, dev]

    pull_request:
        branches: [main]

jobs:
    setup_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: print hello world
              run: echo "Hello World"
            - name: display reamdme file
              run: cat README.md

    build:
        needs: setup_job
        runs-on: ubuntu-latest

        steps:
            - name: display hello
              run: echo hello
    deploy:
        runs-on: ubuntu-latest

        steps:
            - run: echo hello world
